# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Viacheslav Buchkov
title: Quantitative Researcher
email: viacheslav.buchkov@gmail.com
phone: +41 76 291 82 80
location: Zurich, Switzerland

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: v-buchkov
github_username:  v-buchkov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Email
  icon: fas fa-globe
  url: mailto:viacheslav.buchkov@gmail.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Viacheslav and I'm an aspiring quantitative researcher with a total 5 years of experience in Quantitative Asset Management, possessing strong statistical learning, portfolio optimization and derivatives pricing skills.

  ## Research Interests:
  My primary professional and academic research topics of interest are <mark>Quantitative Investment Strategies</mark>, <mark>Structured Products</mark>, <mark>Derivatives Pricing</mark> and <mark>Roboadvisory</mark>.

  ## Programming Skills:
  <mark>Python</mark>, <mark>MATLAB</mark>, <mark>C++</mark>, <mark>Java</mark>, <mark>Golang</mark>, <mark>R</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Raiffeisenbank JSC, Raiffeisen Bank International Group
        link: raiffeisen.ru
        # link_text: boringcompany.com
        sub_title: Senior Officer, Quantitative Investment Strategies, Capital Markets
        caption: July 2023 - Present
        quote: >
          (Moscow, Russia - remote work)
        description: | # this will include new lines to allow paragraphs
            Supervising and leading quant research and product development in:
            * Factor Investing in Equity and Fixed Income
            * Smart Beta Strategies
            * Beta Factor Advisory & Investment Engine
            * Beta Factor Index replication via Reinforcement Learning
            * Financial and non-financial (real estate, salary) cash flows Beta Factorization
            * RUB Interest Rates Beta Strategies
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Product Manager, Prime Brokerage & Investment Products
        caption: April 2022 - June 2023
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Supervised Institutional Brokerage Software Engineering team of 22 engineers
            * Designed architecture of prime brokerage services, planning roadmap and prioritizing initiatives
            * Initializing and project leading new Institutional Prime Brokerage and Investment products
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Quantitative Analyst, Structured Products
        caption: August 2021 - March 2022
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Discovered and implemented over 20 tailor-made investment ideas in equity & credit products, including volatility and correlation-based strategies
            * Researched statistical arbitrage strategies for offshore versus onshore volatility and MOEX FX options correlation trade in EURRUB & USDRUB
            * Developed pricing, delta-hedging, greeks & RWA calculation for linear strategies
            * Engineered Monte Carlo Simulation & Pricing Tool for exotic structured products
            * Designed products continuous valuation and lifecycle management MVP
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Junior Sales Trader, Institutional Fixed Income, Sales&Trading
        caption: March 2021 - July 2021
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Oversaw and led Russian Government Bonds algorithmic market-making
            * Was responsible for client coverage and fixed income flow on 70+ clients
            * Provided coverage for investors on 30+ primary bonds issues & 1 IPO
            * Developed wide network of electronic price sources (brought 26 new market-makers in Bloomberg ALLQ, MarketAxess and BondLink China — mostly via cold outreach)
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Intern, Institutional Fixed Income, Sales&Trading
        caption: August 2020 - February 2021
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Specialized in Fixed Income and REPO execution for over 50 brokerage clients with constant order flow
            * Created Python algorithm for non-screen term REPO pricing, further implemented for brokerage execution
      - layout: top-middle
        title: AriCapital Asset Management
        link: aricapital.ru
        # link_text: boringcompany.com
        sub_title: Intern, Fixed Income & Equity Research
        caption: September 2019 - June 2020
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Published 36 articles on the daily news of financial markets, analyzing the impact on prices of instruments
            * Completed fundamental analysis of equity and debt instruments of the largest international oﬀshore drilling companies with two investment ideas in debt instruments
      - layout: top-middle
        title: Rosbank, Société Générale Group
        link: rosbank.ru
        # link_text: boringcompany.com
        sub_title: Intern, Research, Capital Markets & Investment Banking Department
        caption: July 2019 - August 2019
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            Completed fundamental top-down analysis of the Russian Metals&Mining sector with two investment ideas in debt instruments and two ideas in equity

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ETH Zurich & University of Zurich
        caption: 2024-2026
        sub_title: MSc Quantitative Finance
        quote: >
          Master of Science UZH ETH in Quantitative Finance (Zurich, Switzerland)
        description: | # this will include new lines to allow paragraphs
          The specialized Master program “Master of Science UZH ETH in Quantitative Finance” (MScQF) is a program offered jointly by the University of Zurich and ETH Zurich.

          Ranked number 1 in Europe and on the 7th position worldwide in the RiskNet Quant Finance Master's Guide 2023.

      - layout: top-middle
        title: National Research University Higher School of Economics
        caption: 2022-2024
        sub_title: MSc in Applied Mathematics & Informatics *with Distinction*
        quote: >
          Machine Learning and Data-Intensive Systems, Faculty of Computer Science (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          Relevant courses: Reinforcement Learning (**top-1 of the course**), Deep Learning (10/10), Natural Language Processing (10/10)
          
          **Thesis: “Hedging Derivatives Under Incomplete Markets with Deep Learning” (Grade 10/10, GitHub: https://github.com/v-buchkov/deep-hedging, Pip: _pip install deep_hedging_)**

          **GPA 3.90 / 4.0**

      - layout: top-middle
        title: National Research University Higher School of Economics & University of London
        caption: 2018-2022
        sub_title: Dual degree BSc in Economics and Finance
        quote: >
          International College of Economics and Finance & University of London (under academic direction of London School of Economics) (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          Relevant courses: Statistics (10/10), Principles of Banking and Finance (10/10), Programming and Data Processing (9/10)
          
          **Thesis: “Expected Performance Optimization of Fixed Income Portfolio via Structured Products”**\ **(Grade 10/10, "Best Thesis of Class 2022”, “HSE Scientific Research Challenge 2022” Awardee)**

          **GPA 3.81 / 4.0**

  - title: Additional Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Experts School of Quants
        caption: 2023-2024 (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          **Extracurricular training program in quantitative finance and applied machine learning topics**

          Grade: Top-4 in Final Rating of Students

          Top-1 in Portfolio Optimization and Risk Management Exam

          Top-2 in Equity Derivatives & FX Derivatives Exam
      - layout: left
        title: Avito Analytics Academy
        caption: 2022-2023 (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          **Data Science Engineer Training Program**

          Program from [Top-1 E-Commerce Classified](https://www.similarweb.com/top-websites/e-commerce-and-shopping/classifieds/)
      - layout: left
        title: Bocconi University
        caption: Summer 2019 (Milan, Italy)
        description: | # this will include new lines to allow paragraphs
          **Equity and Venture Financing Summer School Program**

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Winner of Open Hackaton in Quantitative Finance (The Experts School of Quants)
        description: | # this will include new lines to allow paragraphs
          Market order classification for BUY/SELL vs HOLD via ML&DL, including feature selection

      - layout: top-middle
        title: Interest Rate Derivatives - Short Rate (Short SDF) Stochastic Simulation
        link: github.com/v-buchkov/soq-projects/tree/main/short_rate_simulation
        # link_text: Project Website
        additional_links:
          - title: Short Rate (Short SDF) Stochastic Simulation
            icon: fab fa-github
            url: github.com/v-buchkov/soq-projects/tree/main/short_rate_simulation
        description: | # this will include new lines to allow paragraphs
          **(Grade 48/50)** Short rate (short SDF) stochastic simulation using Vasicek model, Hull-White model and LSTM NN.
      
      - layout: top-middle
        title: Portfolio Management - Quantitative Investment Strategy Backtesting
        link: github.com/v-buchkov/soq-projects/tree/main/quantitative_strategy_backtest
        # link_text: Project Website
        additional_links:
          - title: Quantitative Investment Strategy Backtesting
            icon: fab fa-github
            url: github.com/v-buchkov/soq-projects/tree/main/quantitative_strategy_backtest
        description: | # this will include new lines to allow paragraphs
          **(Grade 10/10)** Implemented “Flow Toxicity and Liquidity in a High Frequency World” (Lopez de Prado et al., 2010).
      
      - layout: top-middle
        title: Development of FX Market-Maker Simulator Game
        link: t.me/FXTraderSimulatorBot
        # link_text: Project Website
        additional_links:
          - title: FX Market-Maker Simulator
            icon: fab fa-telegram
            url: t.me/FXTraderSimulatorBot
        description: | # this will include new lines to allow paragraphs
          Designing and programming game for simulating a market-maker’s task for hedging out corporate flow for HSE MSc Derivatives course.
      
      - layout: top-middle
        title: Natural Language Processing-based MOEX FX Straddle Vega and Gamma Trading Strategy
        link: github.com/v-buchkov/hse_volatility_project
        # link_text: Project Website
        additional_links:
          - title: NLP Gamma & Vega Trading Strategy
            icon: fab fa-github
            url: github.com/v-buchkov/hse_volatility_project
        description: | # this will include new lines to allow paragraphs
          **(Grade 9/10)** Modeling of market sentiment in the news, social media and research reports with target to generate consistent prediction of the delta-hedged straddle PnL sign’s classification.
      
      - layout: top-middle
        title: Java Option Pricing Library
        link: github.com/v-buchkov/options-pricer
        # link_text: Project Website
        additional_links:
          - title: Java Option Pricing Library
            icon: fab fa-github
            url: github.com/v-buchkov/options-pricer
        description: | # this will include new lines to allow paragraphs
          Pricing library pet-project, driven by analytical solutions of PDE and Monte Carlo simulations.
      
      - layout: top-middle
        title: Python-based Automatization of Russian Metals&Mining Bonds Fundamental Analysis
        description: | # this will include new lines to allow paragraphs
          **(Grade 10/10)** Developed algorithmic tool for public credit quality prediction, pricing, search for undervalued bonds.

      - layout: top-middle
        title: Macroeconomic Research on US Monetary Policy after 2020
        link: https://www.investing.com/analysis/markets-better-not-lose-their-fed-200523342
        description: | # this will include new lines to allow paragraphs
          Article that studies behavioral inefficiencies, which have arisen from the biased monetary policy in US.
      
      - layout: top-middle
        title: Investment Roboadvising Algorithm
        description: | # this will include new lines to allow paragraphs
          **(Grade 10/10)** Prototype of an automated advisor that outputs mean-variance optimal portfolio.

  - title: Languages
    layout: text
    content: | # this will include new lines to allow paragraphs
      - English (proficient, IELTS 8.0/9.0)
      - Russian (native)

  - title: Hobbies & Sports
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside with my interests in quantitative finance and machine learning some of my other interests and hobbies are:
      - Fencing (captain of city’s team at Cup of Russia)
      - Football (vice-captain of 3 teams in Moscow championships)
      - Modern Russian literature
      - Game Design
      - Poker
      - Skiing

  - title: Thanks for your attention!
    layout: top-middle
    content: | # this will include new lines to allow paragraphs
      ![Trophy](images/trophy.jpg "Trophy")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
