# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Viacheslav Buchkov
title: Quantitative Researcher
email: viacheslav.buchkov@gmail.com
phone: +41 76 291 82 80
location: Zurich, Switzerland

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
# github_username:  sproogen
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: v-buchkov
github_username:  v-buchkov
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Email
  icon: fas fa-globe
  url: mailto:viacheslav.buchkov@gmail.com
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_photo.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Viacheslav and I'm an aspiring quantitative researcher with a total 5 years of experience in Quantitative Asset Management, possessing strong statistical learning, portfolio optimization and derivatives pricing skills.

  My primary professional and academic research topics of interest are <mark>Quantitative Investment Strategies</mark>, <mark>Structured Products</mark> and <mark>Derivatives Pricing</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Raiffeisenbank JSC, Raiffeisen Bank International Group
        link: raiffeisen.ru
        # link_text: boringcompany.com
        sub_title: Senior Officer, Quantitative Investment Strategies, Capital Markets
        caption: July 2023 - Present
        quote: >
          (Moscow, Russia - remote work)
        description: | # this will include new lines to allow paragraphs
            Supervising and leading quant research and product development in:
            * Factor Investing in Equity and Fixed Income
            * Smart Beta Strategies
            * Beta Factor Advisory & Investment Engine
            * Beta Factor Index replication via Reinforcement Learning
            * Financial and non-financial (real estate, salary) cash flows Beta Factorization
            * RUB Interest Rates Beta Strategies
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Product Manager, Prime Brokerage & Investment Products
        caption: April 2022 - June 2023
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Supervised Institutional Brokerage Software Engineering team of 22 engineers
            * Designed architecture of prime brokerage services, planning roadmap and prioritizing initiatives
            * Initializing and project leading new Institutional Prime Brokerage and Investment products
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Quantitative Analyst, Structured Products
        caption: August 2021 - March 2022
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Discovered and implemented over 20 tailor-made investment ideas in equity & credit products, including volatility and correlation-based strategies
            * Researched statistical arbitrage strategies for offshore versus onshore volatility and MOEX FX options correlation trade in EURRUB & USDRUB
            * Developed pricing, delta-hedging, greeks & RWA calculation for linear strategies
            * Engineered Monte Carlo Simulation & Pricing Tool for exotic structured products
            * Designed products continuous valuation and lifecycle management MVP
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Junior Sales Trader, Institutional Fixed Income, Sales&Trading
        caption: March 2021 - July 2021
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Oversaw and led Russian Government Bonds algorithmic market-making
            * Was responsible for client coverage and fixed income flow on 70+ clients
            * Provided coverage for investors on 30+ primary bonds issues & 1 IPO
            * Developed wide network of electronic price sources (brought 26 new market-makers in Bloomberg ALLQ, MarketAxess and BondLink China — mostly via cold outreach)
      - layout: top-middle
        # link_text: boringcompany.com
        sub_title: Intern, Institutional Fixed Income, Sales&Trading
        caption: August 2020 - February 2021
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Specialized in Fixed Income and REPO execution for over 50 brokerage clients with constant order flow
            * Created Python algorithm for non-screen term REPO pricing, further implemented for brokerage execution
      - layout: top-middle
        title: AriCapital Asset Management
        link: aricapital.ru
        # link_text: boringcompany.com
        sub_title: Intern, Fixed Income & Equity Research
        caption: September 2019 - June 2020
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            * Published 36 articles on the daily news of financial markets, analyzing the impact on prices of instruments
            * Completed fundamental analysis of equity and debt instruments of the largest international oﬀshore drilling companies with two investment ideas in debt instruments
      - layout: top-middle
        title: Rosbank, Société Générale Group
        link: rosbank.ru
        # link_text: boringcompany.com
        sub_title: Intern, Research, Capital Markets & Investment Banking Department
        caption: July 2019 - August 2019
        quote: >
          (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
            Completed fundamental top-down analysis of the Russian Metals&Mining sector with two investment ideas in debt instruments and two ideas in equity

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: ETH Zurich & University of Zurich
        caption: 2024-2026
        sub_title: MSc Quantitative Finance
        quote: >
          Master of Science UZH ETH in Quantitative Finance (Zurich, Switzerland)
        description: | # this will include new lines to allow paragraphs
          The specialized Master program “Master of Science UZH ETH in Quantitative Finance” (MScQF) is a program offered jointly by the University of Zurich and ETH Zurich.

          Ranked number 1 in Europe and on the 7th position worldwide in the RiskNet Quant Finance Master's Guide 2023.

      - layout: top-middle
        title: National Research University Higher School of Economics
        caption: 2022-2024
        sub_title: MSc in Applied Mathematics & Informatics *with Distinction*
        quote: >
          Machine Learning and Data-Intensive Systems, Faculty of Computer Science (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          Relevant courses: Reinforcement Learning (**top-1 of the course**), Deep Learning (10/10), Natural Language Processing (10/10)
          **Thesis: “Hedging Derivatives Under Incomplete Markets with Deep Learning” (Grade 10/10, GitHub: https://github.com/v-buchkov/deep-hedging, Pip: _pip install deep_hedging_)**

          **GPA 3.90 / 4.0**

      - layout: top-middle
        title: | # this will include new lines to allow paragraphs
          National Research University Higher School of Economics
          International College of Economics and Finance
          University of London (under academic direction of London School of Economics)
        caption: 2018-2022
        sub_title: MSc in Applied Mathematics & Informatics *with Distinction*
        quote: >
          Machine Learning and Data-Intensive Systems, Faculty of Computer Science (Moscow, Russia)
        description: | # this will include new lines to allow paragraphs
          Relevant courses: Reinforcement Learning (**top-1 of the course**), Deep Learning (10/10), Natural Language Processing (10/10)
          **Thesis: “Hedging Derivatives Under Incomplete Markets with Deep Learning” (Grade 10/10, GitHub: https://github.com/v-buchkov/deep-hedging, Pip: _pip install deep_hedging_)**

          **GPA 3.90 / 4.0**

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
